name: Build and Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # branches:
    #   - master
    tags: 
      - "v*"

jobs:
  # Bundle theme files into argo.zip
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-    
      - run: (cd themes/argo && npm ci --production)
      - run: (cd themes/argo && npm run build) 

      - name: Save theme file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: argo.zip


  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Get theme zip file
        uses: actions/download-artifact@v2
        with:
          name: release

      - name: Create GitHub release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.zip
  

  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Sync with wp-cli
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: /usr/home/${{ secrets.USERNAME }}/deploy.sh
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}